name       : python-spake2
version    : 0.8
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/s/spake2/spake2-0.8.tar.gz : c17a614b29ee4126206e22181f70a406c618d3c6c62ca6d6779bce95e9c926f4
license    : MIT
component  : programming.python
summary    : This library implements the SPAKE2 password-authenticated key exchange
description: |
    This library implements the SPAKE2 password-authenticated key exchange
setup      : |
    %python3_setup
install    : |
    %python3_install
